version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=tw_user
      - POSTGRES_DB=tweetly_db
    ports:
      - '5430:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    
