# Generated by Django 4.2.3 on 2023-08-26 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tweet_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="tags",
        ),
        migrations.DeleteModel(
            name="TweetRetweet",
        ),
    ]
