# Generated by Django 4.2.3 on 2023-08-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_tweet_tags_delete_tweetretweet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="tweet",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="like",
            name="tweet",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AddField(
            model_name="like",
            name="like_count",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="comments",
            field=models.ManyToManyField(
                through="core.TweetComment", to="core.comment"
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="like",
            field=models.ManyToManyField(through="core.TweetLike", to="core.like"),
        ),
        migrations.AddField(
            model_name="tweet",
            name="tags",
            field=models.ManyToManyField(through="core.TweetTag", to="core.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tweetcomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.comment",
            ),
        ),
        migrations.AlterField(
            model_name="tweetcomment",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                to="core.tweet",
            ),
        ),
    ]
