# Generated by Django 4.2.3 on 2023-08-31 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_comment_tweet_remove_comment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweetlike",
            name="like",
        ),
        migrations.AddField(
            model_name="tweetlike",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tweet",
            name="like",
            field=models.ManyToManyField(
                related_name="liked_tweets",
                through="core.TweetLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
