# Generated by Django 4.2.3 on 2023-09-01 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_tweetlike_like_tweetlike_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="retweets",
            field=models.ManyToManyField(
                related_name="retweeted_tweets",
                through="core.Retweet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
