# Generated by Django 4.2.3 on 2023-09-04 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_real",
        ),
    ]
